export const collaborateursQualification = [
  {
    id: 1,
    phase: "qualification",
    matricule: "MAT001",
    nom: "Ahmed Ben Ali",
    prenom: "Ahmed",
    fonction: "Operateur",
    centre_cout: "CC-100",
    groupe: "Assemblage A",
    competence: "Cablage",
    contre_maitre: "Hichem Trabelsi",
    segment: "Production",
    gender: "M",
    num_tel: "21620101010",
    date_recrutement: "15/01/2024",
    anciennete: 2,
    statut: "Qualifie",
    formations: 5,
    derniereFormation: "10/01/2026",
  },
  {
    id: 2,
    phase: "qualification",
    matricule: "MAT002",
    nom: "Fatima Zahra",
    prenom: "Fatima",
    fonction: "Controleur Qualite",
    centre_cout: "CC-210",
    groupe: "Qualite Ligne 2",
    competence: "Audit Produit",
    contre_maitre: "Meriem Kacem",
    segment: "Qualite",
    gender: "F",
    num_tel: "21622112233",
    date_recrutement: "20/06/2023",
    anciennete: 3,
    statut: "Qualifie",
    formations: 8,
    derniereFormation: "05/02/2026",
  },
  {
    id: 3,
    phase: "indection",
    matricule: "MAT003",
    nom: "Mohamed Salhi",
    prenom: "Mohamed",
    fonction: "Technicien",
    centre_cout: "CC-320",
    groupe: "Maintenance Electrique",
    competence: "Diagnostic",
    contre_maitre: "Nizar Riahi",
    segment: "Maintenance",
    gender: "M",
    num_tel: "21650111222",
    date_recrutement: "10/03/2025",
    anciennete: 1,
    statut: "Non associe",
    formations: 3,
    derniereFormation: "15/12/2025",
  },
  {
    id: 4,
    phase: "qualification",
    matricule: "MAT004",
    nom: "Nadia Mansouri",
    prenom: "Nadia",
    fonction: "Chef d'equipe",
    centre_cout: "CC-140",
    groupe: "Assemblage B",
    competence: "Management Equipe",
    contre_maitre: "Aymen Gharbi",
    segment: "Production",
    gender: "F",
    num_tel: "21698111000",
    date_recrutement: "01/09/2022",
    anciennete: 4,
    statut: "Qualifie",
    formations: 12,
    derniereFormation: "28/01/2026",
  },
  {
    id: 5,
    phase: "indection",
    matricule: "MAT005",
    nom: "Youssef El Amrani",
    prenom: "Youssef",
    fonction: "Magasinier",
    centre_cout: "CC-410",
    groupe: "Stock Central",
    competence: "Gestion Stock",
    contre_maitre: "Sami Ben Othman",
    segment: "Logistique",
    gender: "M",
    num_tel: "21628765432",
    date_recrutement: "05/11/2024",
    anciennete: 1,
    statut: "Non associe",
    formations: 2,
    derniereFormation: "20/05/2025",
  },
  {
    id: 6,
    phase: "qualification",
    matricule: "MAT006",
    nom: "Samira Bennani",
    prenom: "Samira",
    fonction: "Assistante RH",
    centre_cout: "CC-520",
    groupe: "Ressources Humaines",
    competence: "Onboarding",
    contre_maitre: "Yasmine Gmati",
    segment: "Support",
    gender: "F",
    num_tel: "21693123456",
    date_recrutement: "14/02/2023",
    anciennete: 3,
    statut: "Qualifie",
    formations: 6,
    derniereFormation: "18/01/2026",
  },
  {
    id: 7,
    phase: "indection",
    matricule: "MAT007",
    nom: "Karim Belkacem",
    prenom: "Karim",
    fonction: "Operateur",
    centre_cout: "CC-101",
    groupe: "Assemblage C",
    competence: "Ergonomie Poste",
    contre_maitre: "Hatem Baccar",
    segment: "Production",
    gender: "M",
    num_tel: "21629001122",
    date_recrutement: "12/08/2024",
    anciennete: 1,
    statut: "Depassement",
    formations: 4,
    derniereFormation: "20/08/2025",
  },
];

export const statutOptions = ["Non associe", "En cours", "Qualifie", "Depassement"];
export const MAX_LAST_FORMATION_AGE_DAYS = 90;
